server:
  port: 9001

spring:  application:    name: jt-cart-consumer

eureka:  client:
    service-url:      defaultZone: http://user:password123@localhost:8761/eureka
      
logging:  level:    root: INFO